tasks:
  - init: |
      wget -qO- https://www.mongodb.org/static/pgp/server-7.0.asc | sudo tee /etc/apt/trusted.gpg.d/server-7.0.asc && echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list && sudo apt update && sudo apt install -y mongodb-mongosh mongodb-database-tools && echo "alias MONGO-ATLAS='mongosh "mongodb+srv://tvy6kv:DHq3HqvJBE94GL3g@cluster0.u2p8mcm.mongodb.net/" --apiVersion 1'" >> ~/.bashrc
      gp sync-done installation
  - init: gp sync-await installation
    command: source ~/.bashrc
  - name: pip
    command: pip install -r requirements.txt && exit
